/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import controle.CarroControle;
import controle.MarcaControle;
import controle.PessoaControle;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.Carro;
import modelo.Marca;

/**
 *
 * @author Rig
 */
public class CarroGUI extends javax.swing.JFrame {
     private Boolean alterando;
     private Carro objeto;
     private List<Marca> lmarcas = new ArrayList<Marca>();
     private Marca marcaSelecionada = new Marca();
     List<Carro> c = null;

     
   
     
     
    /**
     * Creates new form PessoGUI
     */
    public CarroGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtDescricao = new javax.swing.JTextField();
        TxtCor = new javax.swing.JTextField();
        BtnNovo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BtnAlterar = new javax.swing.JButton();
        BtnGravar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cboMarca = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        TxtAno = new javax.swing.JTextField();
        lstCarros = new javax.swing.JList();
        BtnExcluir = new javax.swing.JButton();
        BtnFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel3.setText("DESCRICAO");

        jLabel5.setText("COR");

        TxtCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCorActionPerformed(evt);
            }
        });

        BtnNovo.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        BtnNovo.setText("NOVO");
        BtnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNovoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setText("             CADASTRO DO CARRO");

        BtnAlterar.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        BtnAlterar.setText("ALTERAR");
        BtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAlterarActionPerformed(evt);
            }
        });

        BtnGravar.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        BtnGravar.setText("GRAVAR");
        BtnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGravarActionPerformed(evt);
            }
        });

        jLabel2.setText("MARCA");

        cboMarca.setToolTipText("");
        cboMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMarcaActionPerformed(evt);
            }
        });

        jLabel6.setText("ANO");

        TxtAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtAnoActionPerformed(evt);
            }
        });

        lstCarros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstCarrosMouseClicked(evt);
            }
        });

        BtnExcluir.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        BtnExcluir.setText("EXCLUIR");
        BtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExcluirActionPerformed(evt);
            }
        });

        BtnFechar.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        BtnFechar.setText("FECHAR");
        BtnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtCor, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lstCarros, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BtnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnGravar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(TxtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtCor, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lstCarros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAlterar)
                    .addComponent(BtnNovo)
                    .addComponent(BtnGravar)
                    .addComponent(BtnExcluir)
                    .addComponent(BtnFechar))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private int Checar() {
       int a = 0;
       if (TxtDescricao.getText().trim().equals("") | TxtCor.getText().trim().equals("") | TxtAno.getText().trim().equals("")) {
           JOptionPane.showMessageDialog(this, "Os campos devem ser preenchidos antes de gravar.");
           return a = 1;
       }

       return a;
    }
    
    private void exibirLista(){
     CarroControle lista = new CarroControle();
     try {
         lista.atualizarListaCarros(lstCarros);
         limparCampos();
     } catch (Exception ex) {
         JOptionPane.showMessageDialog(this, "Erro ao atualizar lista de carros " + ex.getMessage());
     }
     }
    private void TxtCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCorActionPerformed

    private void BtnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNovoActionPerformed
        limparCampos();
    }//GEN-LAST:event_BtnNovoActionPerformed

    private void BtnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGravarActionPerformed
        int a = Checar();
        if (a == 0) {
            try {
                CarroControle c = new CarroControle();
               Carro carro = new Carro();
            
                if (marcaSelecionada==null){
                    JOptionPane.showMessageDialog(null, "Marca nao selecionada!");
                    return;
                } else {
                    carro.setMarca(marcaSelecionada);
                }
                
                carro.setDescricao(TxtDescricao.getText());
                carro.setCor(TxtCor.getText());
                carro.setAno(Integer.parseInt(TxtAno.getText()));        
                //metodo tem que ser privado!!!!
                c.cadastrar(carro,lstCarros);
                exibirLista();
                JOptionPane.showMessageDialog(null, "Registrado com sucesso!");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Erro ao cadastrar Carro " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_BtnGravarActionPerformed
 //percorre toda a combobox e comparao id da marca do carro selecionado
    public void setSelectedValue(int idMarca)
    {
        Marca item;
        for (int i = 0; i < cboMarca.getItemCount(); i++)
        {
            item = (Marca)cboMarca.getItemAt(i);
            if (item.getId() == idMarca)
            {
                cboMarca.setSelectedIndex(i);
                break;
            }
        }
    }                
    private void cboMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMarcaActionPerformed
        marcaSelecionada = (Marca) cboMarca.getSelectedItem();
    }//GEN-LAST:event_cboMarcaActionPerformed

    private void TxtAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtAnoActionPerformed

    private void BtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAlterarActionPerformed
        alterando = true;
        arrumarInterfaceEdicao();
        //exibirDados(); 
    }//GEN-LAST:event_BtnAlterarActionPerformed

    private void lstCarrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstCarrosMouseClicked
       
        if(lstCarros.getSelectedValue()!=null){
             Carro c = (Carro) lstCarros.getSelectedValue();
             TxtDescricao.setText(c.getDescricao());
            TxtCor.setText(c.getCor());
            TxtAno.setText(String.valueOf(c.getAno()));
            setSelectedValue(c.getMarca().getId());
        }
        
        
    }//GEN-LAST:event_lstCarrosMouseClicked

    private void BtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExcluirActionPerformed
           try {
            Carro apagar = null;
            apagar = (Carro) lstCarros.getSelectedValue();

            if (apagar != null) {
                CarroControle c = new CarroControle();
                c.excluir(apagar);                
                JOptionPane.showMessageDialog(null, "Excluido com sucesso!");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao excluir registroo");
        }
    }//GEN-LAST:event_BtnExcluirActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
           exibirLista();       
                      
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        MarcaControle m = new MarcaControle();         
         try {
             lmarcas = m.listarMarcas();
         } catch (SQLException ex) {
             Logger.getLogger(CarroGUI.class.getName()).log(Level.SEVERE, null, ex);
         }
        
         cboMarca.removeAllItems();
         for(Marca marca: lmarcas){
             cboMarca.addItem(marca);
         }
    }//GEN-LAST:event_formWindowOpened

    private void BtnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtnFecharActionPerformed

    private void arrumarInterfaceEdicao() {
        BtnNovo.setEnabled(false);
        BtnAlterar.setEnabled(false);
        BtnNovo.setEnabled(false);       
        BtnGravar.setEnabled(true);
        
        TxtDescricao.setEditable(true);
        TxtCor.setEditable(true);
        TxtAno.setEditable(true);       

    }
 /*   private void exibirDados() {
        objeto = (Carro) lstCarros.getSelectedValue();
        TxtDescricao.setText(objeto.getDescricao());
        TxtCor.setText(objeto.getCor());
        TxtAno.setText(String.valueOf(objeto.getAno()));
        

    }*/
       
    private void limparCampos() {
        
        TxtDescricao.setText("");
        TxtCor.setText("");
        TxtAno.setText("");
       
    }
    
  
    public static void main(String args[]) {
  
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarroGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAlterar;
    private javax.swing.JButton BtnExcluir;
    private javax.swing.JButton BtnFechar;
    private javax.swing.JButton BtnGravar;
    private javax.swing.JButton BtnNovo;
    private javax.swing.JTextField TxtAno;
    private javax.swing.JTextField TxtCor;
    private javax.swing.JTextField TxtDescricao;
    private javax.swing.JComboBox cboMarca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList lstCarros;
    // End of variables declaration//GEN-END:variables
}
