/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import controle.CarroControle;
import controle.PessoaControle;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.Carro;
import modelo.Pessoa;

/**
 *
 * @author Rig
 */
public class PessoaGUI extends javax.swing.JFrame {
    DateTimeFormatter formatador = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    private Pessoa pessoa = new Pessoa();
    private Carro carro;
    private Boolean alterando;
    
    
   
    
  
     private int checkCampos() {
        int a = 0;
        if (TxtNome.getText().trim().equals("") | TxtCpf.getText().trim().equals("") | TxtData.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Todos os campos devem ser preenchidos antes de gravar.");
            return a = 1;
        }
        return a;
    }
    /**
     * Creates new form CarroGUI
     */
    public PessoaGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BtnGravar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtNome = new javax.swing.JTextField();
        TxtCpf = new javax.swing.JTextField();
        TxtData = new javax.swing.JTextField();
        BtnNovo = new javax.swing.JButton();
        lstCarros = new javax.swing.JList();
        BtnFechar = new javax.swing.JButton();
        BtnSim = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        BtnExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstPessoas = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setText("             CADASTRO DE PESSOAS ");

        BtnGravar.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        BtnGravar.setText("GRAVAR");
        BtnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGravarActionPerformed(evt);
            }
        });

        jLabel2.setText("NOME");

        jLabel3.setText("CPF");

        jLabel5.setText("DATA DE NASCIMENTO");

        TxtData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDataActionPerformed(evt);
            }
        });

        BtnNovo.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        BtnNovo.setText("NOVO");
        BtnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNovoActionPerformed(evt);
            }
        });

        lstCarros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstCarrosMouseClicked(evt);
            }
        });

        BtnFechar.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        BtnFechar.setText("FECHAR");
        BtnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFecharActionPerformed(evt);
            }
        });

        BtnSim.setText("Sim");
        BtnSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimActionPerformed(evt);
            }
        });

        jLabel6.setText("POSSUI CARRO?");

        BtnExcluir.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        BtnExcluir.setText("EXCLUIR");
        BtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExcluirActionPerformed(evt);
            }
        });

        lstPessoas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstPessoasValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstPessoas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(BtnGravar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lstCarros, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(73, 73, 73))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TxtData, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel2)
                                                    .addComponent(jLabel3))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(TxtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(TxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(BtnSim)))
                                        .addGap(18, 18, 18)))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(13, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jLabel4)
                .addContainerGap(313, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TxtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(TxtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(BtnSim))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lstCarros, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnGravar)
                    .addComponent(BtnNovo)
                    .addComponent(BtnFechar)
                    .addComponent(BtnExcluir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNovoActionPerformed
        limparCampos();
    }//GEN-LAST:event_BtnNovoActionPerformed

    private void BtnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGravarActionPerformed
PessoaControle check = new PessoaControle();
        LocalDate nascimento = null;
        //DateTimeFormatter formatador = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        boolean ok = false;
        int checkCampo = checkCampos();

        if (checkCampo == 0) {
            try {
                String dia = TxtData.getText().substring(0, 2);
                String mes = TxtData.getText().substring(3, 5);
                String ano = TxtData.getText().substring(6, 10);
                nascimento = (LocalDate.of(Integer.parseInt(ano), Integer.parseInt(mes), Integer.parseInt(dia)));          //Receber data

                ok = check.checarNascimento(nascimento);

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "A data deve estar no formato dd/MM/aaaa");
                return;
            }

            try {
                if (ok == false & BtnSim.isSelected() == true) {
                    JOptionPane.showMessageDialog(null, "É necessário ser maior de 18 anos para cadastrar um carro");
                } else {
                    PessoaControle ctrlpessoa = new PessoaControle();                   

                    pessoa.setNome(TxtNome.getText());
                    pessoa.setCpf(TxtCpf.getText());
                    pessoa.setDatanasc(nascimento);
                    if (BtnSim.isSelected() == true) {
                        pessoa.setCarro((Carro) lstCarros.getSelectedValue());
                        ctrlpessoa.cadastrar(pessoa);
                    } else {
                        pessoa.setCarro(null);
                        ctrlpessoa.cadastrarSemCarro(pessoa);
                    }
                    exibirDados();
                    JOptionPane.showMessageDialog(null, "Registrado com sucesso!");
                    TxtCpf.setText("");
                    TxtData.setText("");
                    TxtNome.setText("");
                    BtnSim.setSelected(false);

                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Erro ao cadastrar pessoa" + ex);
            }
          
        }
    }//GEN-LAST:event_BtnGravarActionPerformed

    private void TxtDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDataActionPerformed

    private void lstCarrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstCarrosMouseClicked
         
        if(lstCarros.getSelectedValue()!=null){
            
            //Pessoa p = (Pessoa) lstPessoas.getSelectedValue();
            Carro carro =(Carro) lstCarros.getSelectedValue();            
            pessoa.setCarro(carro);
            /*TxtNome.setText(p.getNome());
            TxtCpf.setText(p.getCpf());
            TxtData.setText(p.getDatanasc().format(formatador));*/
            
        }
        
    }//GEN-LAST:event_lstCarrosMouseClicked
  
    private void BtnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtnFecharActionPerformed

    private void BtnSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimActionPerformed
        if (BtnSim.isSelected() == true) {
            lstCarros.setEnabled(true);
        } else {
            CarroControle lista = new CarroControle();
            lstCarros.setEnabled(false);
            try {
                lista.atualizarListaCarros(lstCarros);
            } catch (SQLException ex) {
                Logger.getLogger(PessoaGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_BtnSimActionPerformed

    private void BtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExcluirActionPerformed
        try {
            Pessoa apagar = null;
            apagar = (Pessoa) lstPessoas.getSelectedValue();

            if (apagar != null) {
                PessoaControle c = new PessoaControle();
                c.excluir(apagar);                
                JOptionPane.showMessageDialog(null, "Excluido com sucesso!");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao excluir registro");
        }
        
    }//GEN-LAST:event_BtnExcluirActionPerformed

    private void lstPessoasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstPessoasValueChanged
        
        pessoa = (Pessoa)lstPessoas.getSelectedValue();
        TxtNome.setText(pessoa.getNome());
        TxtCpf.setText(pessoa.getCpf());
        TxtData.setText(pessoa.getDatanasc().format(formatador));

        //dadosCarro(pessoa);

    }//GEN-LAST:event_lstPessoasValueChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    exibirDados();
    }//GEN-LAST:event_formWindowOpened

   

    

   private void exibirDados() {      
        PessoaControle lista = new PessoaControle();
     try {
         lista.atualizarListaPessoas(lstPessoas);
         limparCampos();
     } catch (Exception ex) {
         JOptionPane.showMessageDialog(this, "Erro ao atualizar lista de pessoas " + ex.getMessage());
     }
     }
        /*TxtNome.setText(objeto.getNome());
        TxtCpf.setText(objeto.getCpf());
        TxtData.setText(objeto.getDatanasc().format(formatador));*/

    

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PessoaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PessoaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PessoaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PessoaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PessoaGUI().setVisible(true);
            }
        });

    }
     
    private void limparCampos() {
        TxtNome.setText("");
        TxtCpf.setText("");
        TxtData.setText("");

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnExcluir;
    private javax.swing.JButton BtnFechar;
    private javax.swing.JButton BtnGravar;
    private javax.swing.JButton BtnNovo;
    private javax.swing.JRadioButton BtnSim;
    private javax.swing.JTextField TxtCpf;
    private javax.swing.JTextField TxtData;
    private javax.swing.JTextField TxtNome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lstCarros;
    private javax.swing.JList lstPessoas;
    // End of variables declaration//GEN-END:variables
}
